# Generated by Django 4.2.28 on 2026-04-14 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEnterprise',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_column='tx_code', help_text='Codigo unico da unidade organizacional.', max_length=100, verbose_name='Code')),
                ('kind', models.CharField(db_column='tx_kind', default='unit', max_length=50, verbose_name='Kind')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical enterprise',
                'verbose_name_plural': 'historical enterprises',
                'db_table': '"history"."enterprise_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_column='tx_code', help_text='Codigo unico da unidade organizacional.', max_length=100, verbose_name='Code')),
                ('kind', models.CharField(db_column='tx_kind', default='unit', max_length=50, verbose_name='Kind')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='organizatio_cs_acti_c02500_idx'), models.Index(fields=['name'], name='organizatio_tx_name_18a108_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='enterprise',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_enterprise_code'),
        ),
    ]
