# Generated by Django 4.2.28 on 2026-04-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enterprise',
            new_name='organizatio_cs_acti_88c8e6_idx',
            old_name='organizatio_cs_acti_c02500_idx',
        ),
        migrations.RenameIndex(
            model_name='enterprise',
            new_name='organizatio_tx_name_2ba9cb_idx',
            old_name='organizatio_tx_name_18a108_idx',
        ),
    ]
