# Generated by Django 4.2.28 on 2026-04-22 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_column='tx_code', max_length=100, verbose_name='Code')),
                ('kind', models.CharField(choices=[('company', 'Company'), ('ngo', 'NGO'), ('government', 'Government'), ('education', 'Education')], db_column='tx_kind', default='company', max_length=32, verbose_name='Kind')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TherapyGroup',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=160, verbose_name='Name')),
                ('focus', models.CharField(db_column='tx_focus', max_length=180, verbose_name='Focus')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('invited', 'Invited'), ('scheduled', 'Scheduled')], db_column='tx_status', default='suggested', max_length=24, verbose_name='Status')),
                ('facilitator_name', models.CharField(blank=True, db_column='tx_facilitator_name', default='', max_length=160, verbose_name='Facilitator name')),
                ('next_session_at', models.DateTimeField(blank=True, db_column='dt_next_session_at', null=True, verbose_name='Next session at')),
                ('enterprise', models.ForeignKey(db_column='id_enterprise', on_delete=django.db.models.deletion.CASCADE, related_name='therapy_groups', to='enterprise.enterprise', verbose_name='Enterprise')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TherapyGroupMember',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('group', models.ForeignKey(db_column='id_therapy_group', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='enterprise.therapygroup', verbose_name='Therapy group')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='therapy_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['group_id', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTherapyGroupMember',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_column='id_therapy_group', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprise.therapygroup', verbose_name='Therapy group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_column='id_user', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical therapy group member',
                'verbose_name_plural': 'historical therapy group members',
                'db_table': '"history"."therapy_group_member_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTherapyGroup',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=160, verbose_name='Name')),
                ('focus', models.CharField(db_column='tx_focus', max_length=180, verbose_name='Focus')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('invited', 'Invited'), ('scheduled', 'Scheduled')], db_column='tx_status', default='suggested', max_length=24, verbose_name='Status')),
                ('facilitator_name', models.CharField(blank=True, db_column='tx_facilitator_name', default='', max_length=160, verbose_name='Facilitator name')),
                ('next_session_at', models.DateTimeField(blank=True, db_column='dt_next_session_at', null=True, verbose_name='Next session at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enterprise', models.ForeignKey(blank=True, db_column='id_enterprise', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprise.enterprise', verbose_name='Enterprise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical therapy group',
                'verbose_name_plural': 'historical therapy groups',
                'db_table': '"history"."therapy_group_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEnterpriseCommercialProfile',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('tax_id', models.CharField(blank=True, db_column='tx_tax_id', default='', max_length=32, verbose_name='Tax ID')),
                ('contact_name', models.CharField(blank=True, db_column='tx_contact_name', default='', max_length=160, verbose_name='Contact name')),
                ('contact_email', models.EmailField(blank=True, db_column='tx_contact_email', default='', max_length=256, verbose_name='Contact email')),
                ('company_size', models.CharField(blank=True, db_column='tx_company_size', default='', max_length=40, verbose_name='Company size')),
                ('plan_id', models.CharField(blank=True, db_column='tx_plan_id', default='', max_length=40, verbose_name='Plan ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enterprise', models.ForeignKey(blank=True, db_column='id_enterprise', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprise.enterprise', verbose_name='Enterprise')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical enterprise commercial profile',
                'verbose_name_plural': 'historical enterprise commercial profiles',
                'db_table': '"history"."enterprise_commercial_profile_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEnterprise',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_column='tx_code', max_length=100, verbose_name='Code')),
                ('kind', models.CharField(choices=[('company', 'Company'), ('ngo', 'NGO'), ('government', 'Government'), ('education', 'Education')], db_column='tx_kind', default='company', max_length=32, verbose_name='Kind')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical enterprise',
                'verbose_name_plural': 'historical enterprises',
                'db_table': '"history"."enterprise_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EnterpriseCommercialProfile',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('tax_id', models.CharField(blank=True, db_column='tx_tax_id', default='', max_length=32, verbose_name='Tax ID')),
                ('contact_name', models.CharField(blank=True, db_column='tx_contact_name', default='', max_length=160, verbose_name='Contact name')),
                ('contact_email', models.EmailField(blank=True, db_column='tx_contact_email', default='', max_length=256, verbose_name='Contact email')),
                ('company_size', models.CharField(blank=True, db_column='tx_company_size', default='', max_length=40, verbose_name='Company size')),
                ('plan_id', models.CharField(blank=True, db_column='tx_plan_id', default='', max_length=40, verbose_name='Plan ID')),
                ('enterprise', models.OneToOneField(db_column='id_enterprise', on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='enterprise.enterprise', verbose_name='Enterprise')),
            ],
            options={
                'ordering': ['enterprise_id'],
            },
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['name', 'active'], name='enterprise__tx_name_cd11d7_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['code', 'active'], name='enterprise__tx_code_84fc13_idx'),
        ),
        migrations.AddConstraint(
            model_name='enterprise',
            constraint=models.UniqueConstraint(fields=('code',), name='uq_enterprise_code'),
        ),
        migrations.AddIndex(
            model_name='therapygroupmember',
            index=models.Index(fields=['group', 'active'], name='enterprise__id_ther_5cce84_idx'),
        ),
        migrations.AddIndex(
            model_name='therapygroupmember',
            index=models.Index(fields=['user', 'active'], name='enterprise__id_user_2f7017_idx'),
        ),
        migrations.AddConstraint(
            model_name='therapygroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uq_therapy_group_member'),
        ),
        migrations.AddIndex(
            model_name='therapygroup',
            index=models.Index(fields=['enterprise', 'active'], name='enterprise__id_ente_7c523f_idx'),
        ),
        migrations.AddIndex(
            model_name='therapygroup',
            index=models.Index(fields=['status', 'active'], name='enterprise__tx_stat_197189_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisecommercialprofile',
            index=models.Index(fields=['enterprise', 'active'], name='enterprise__id_ente_33cd39_idx'),
        ),
    ]
