# Generated by Codex on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_article_watchdevicestatus_recommendation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="department",
            field=models.CharField(blank=True, db_column="tx_department", default="", max_length=120, verbose_name="Department"),
        ),
        migrations.AddField(
            model_name="historicalemployeeprofile",
            name="department",
            field=models.CharField(blank=True, db_column="tx_department", default="", max_length=120, verbose_name="Department"),
        ),
    ]
