# Generated by Django 4.2.28 on 2026-04-18 05:11

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS history'),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('username', models.CharField(db_column='tx_username', max_length=64, verbose_name='Username')),
                ('email', models.EmailField(blank=True, db_column='tx_email', max_length=256, null=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, db_column='tx_name', max_length=256, null=True, verbose_name='Name')),
                ('desired_name', models.CharField(blank=True, db_column='tx_desired_name', max_length=256, null=True, verbose_name='Desired name')),
                ('check_show_again', models.BooleanField(db_column='cs_check_show_again', default=True, verbose_name='Check show again')),
                ('last_login_language', models.CharField(blank=True, choices=[('pt-BR', 'Portuguese (Brazil)'), ('en-US', 'English (US)')], db_column='tx_last_login_language', max_length=5, null=True, verbose_name='Last login language')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(db_column='cs_staff', default=False, verbose_name='Staff status')),
                ('is_default', models.BooleanField(db_column='cs_default', default=False, verbose_name='Default user')),
                ('regime', models.CharField(blank=True, choices=[('0', 'Home office'), ('1', 'Hybrid'), ('2', 'Local')], db_column='cs_regime', default='0', max_length=1, null=True, verbose_name='Regime')),
                ('admission_date', models.DateField(blank=True, db_column='dt_admission_date', null=True, verbose_name='Admission date')),
                ('birth_date', models.DateField(blank=True, db_column='dt_birth_date', null=True, verbose_name='Birth date')),
                ('resignation_date', models.DateField(blank=True, db_column='dt_resignation_date', null=True, verbose_name='Resignation date')),
                ('cpf', models.CharField(blank=True, db_column='tx_cpf', max_length=11, null=True, verbose_name='CPF')),
                ('github', models.CharField(blank=True, db_column='tx_github', max_length=1024, null=True, verbose_name='GitHub')),
                ('linkedin', models.CharField(blank=True, db_column='tx_linkedin', max_length=1024, null=True, verbose_name='LinkedIn')),
                ('external', models.BooleanField(db_column='cs_user_is_external', default=False, verbose_name='External user')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountUserGroup',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('group', models.ForeignKey(db_column='id_group', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_user_groups', to='auth.group', verbose_name='Group')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_user_groups', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'account_user_groups',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', through='accounts.AccountUserGroup', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='RecoveryPassword',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('code', models.SlugField(db_column='tx_code', max_length=6, verbose_name='Code')),
                ('expiration_date', models.DateTimeField(db_column='dt_expiration_date', verbose_name='Expiration date')),
                ('checked_date', models.BooleanField(blank=True, db_column='cs_checked_date', null=True, verbose_name='Checked date')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recovery_passwords', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'account_code',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'active'], name='account_cod_id_user_32f906_idx'), models.Index(fields=['code', 'active'], name='account_cod_tx_code_8ad576_idx'), models.Index(fields=['expiration_date'], name='account_cod_dt_expi_6e36cc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='accountusergroup',
            index=models.Index(fields=['user', 'active'], name='account_use_id_user_5aab3a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountusergroup',
            index=models.Index(fields=['group', 'active'], name='account_use_id_grou_f4abe7_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountusergroup',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='uq_account_user_group'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_tx_user_ffd244_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_tx_emai_87f3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_staff'], name='accounts_us_cs_acti_d61d49_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username',), name='uq_user_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uq_user_email_not_null'),
        ),
    ]
